import '../tokens/colors.dart';
import 'package:flutter/material.dart';

class DefaultColorsInterface {
  const DefaultColorsInterface({
    this.black = Colors.black,
    this.white = Colors.white,
    this.primaryColor = DefaultColors.primaryColor,
    this.tertiaryColor = DefaultColors.tertiaryColor,
    this.contrastColor = DefaultColors.contrastColor,
    this.dangerColor = DefaultColors.dangerColor,
    this.primarySwatch = DefaultColors.primarySwatch,
    this.transparentblack = DefaultColors.transparentblack,
    this.greyishBrown = DefaultColors.greyishBrown,
    this.dividerColor = DefaultColors.dividerColor,
    this.disabledColor = DefaultColors.disabledColor,
    this.hintColor = DefaultColors.hintColor,
    this.darkBrown = DefaultColors.darkBrown,
    this.whiteSecundary = DefaultColors.whiteSecundary,
    this.whiteTertiary = DefaultColors.whiteTertiary,
    this.graySecondary = DefaultColors.graySecondary,
    this.darkGray = DefaultColors.darkGray,
    this.silver = DefaultColors.silver,
    this.primaryLigth = DefaultColors.primaryLigth,
    this.ice = DefaultColors.ice,
    this.greenishWhite = DefaultColors.greenishWhite,
    this.blackSecondary = DefaultColors.blackSecondary,
    this.darkBlack = DefaultColors.darkBlack,
    this.disabledButtonColor = DefaultColors.disabledButtonColor,
    this.blueAccent = DefaultColors.blueAccent,
    this.lightGray = DefaultColors.lightGray,
    this.quickSilver = DefaultColors.quickSilver,
    this.blackOlive = DefaultColors.blackOlive,
    this.japaneseIndigo = DefaultColors.japaneseIndigo,
    this.sunsetOrange = DefaultColors.sunsetOrange,
    this.pearlAqua = DefaultColors.pearlAqua,
    this.graniteGray = DefaultColors.graniteGray,
    this.blackOpaque = DefaultColors.blackOpaque,
    this.lightSilver = DefaultColors.lightSilver,
    this.silverChalice = DefaultColors.silverChalice,
    this.charlestonGreen = DefaultColors.charlestonGreen,
    this.whiteGrey = DefaultColors.whiteGrey,
    this.blackGrey = DefaultColors.blackGrey,
    this.aeroBlue = DefaultColors.aeroBlue,
    this.cultured = DefaultColors.cultured,
    this.silverSand = DefaultColors.silverSand,
    this.philippineGray = DefaultColors.philippineGray,
    this.richBlack = DefaultColors.richBlack,
    this.mediumAquamarina = DefaultColors.mediumAquamarina,
    this.deepSaffron = DefaultColors.deepSaffron,
    this.darkCharcoal = DefaultColors.darkCharcoal,
    this.caribbeanGreen = DefaultColors.caribbeanGreen,
    this.aliceBlue = DefaultColors.aliceBlue,
    this.tintedIce = DefaultColors.tintedIce,
    this.raisinBlack = DefaultColors.raisinBlack,
    this.antiFlashWhite = DefaultColors.antiFlashWhite,
    this.chineseSilver = DefaultColors.chineseSilver,
    this.philippineYellow = DefaultColors.philippineYellow,
    this.mangoGreen = DefaultColors.mangoGreen,
    this.vividMalachite = DefaultColors.vividMalachite,
    this.candyPink = DefaultColors.candyPink,
    this.mistyRose = DefaultColors.mistyRose,
    this.cosmicLatte = DefaultColors.cosmicLatte,
    this.mintCream = DefaultColors.mintCream,
    this.myrtleGreen = DefaultColors.myrtleGreen,
    this.outerSpace = DefaultColors.outerSpace,
    this.sacramentoStateGreen = DefaultColors.sacramentoStateGreen,
    this.salem = DefaultColors.salem,
    this.mediumGrey = DefaultColors.mediumGrey,
    this.lemon = DefaultColors.lemon,
    this.greenLight = DefaultColors.greenLight,
    this.orange = DefaultColors.orange,
    this.orangeLight = DefaultColors.orangeLight,
    this.checkedGreen = DefaultColors.checkedGreen,
    this.oceanInABowl = DefaultColors.oceanInABowl,
    this.errorLight = DefaultColors.errorLight,
    this.deepIndianRed = DefaultColors.deepIndianRed,
    this.bangladeshGreen = DefaultColors.bangladeshGreen,
    this.gray = DefaultColors.gray,
    this.davysGrey = DefaultColors.davysGrey,
    this.lightSlver = DefaultColors.lightSlver,
    this.paleAquamarine = DefaultColors.paleAquamarine,
    this.cadmiumOrange = DefaultColors.cadmiumOrange,
    this.bronze = DefaultColors.bronze,
    this.lightGra = DefaultColors.lightGra,
    this.mustard = DefaultColors.mustard,
    this.meatBrown = DefaultColors.meatBrown,
    this.sonicSilver = DefaultColors.sonicSilver,
    this.eerieBlack = DefaultColors.eerieBlack,
    this.celadonGreen = DefaultColors.celadonGreen,
    this.warmBlack = DefaultColors.warmBlack,
  });

  final Color black;
  final Color white;
  final Color primaryColor;
  final Color tertiaryColor;
  final Color contrastColor;
  final Color dangerColor;
  final Color primarySwatch;
  final Color transparentblack;
  final Color greyishBrown;
  final Color dividerColor;
  final Color disabledColor;
  final Color hintColor;
  final Color darkBrown;
  final Color whiteSecundary;
  final Color whiteTertiary;
  final Color graySecondary;
  final Color darkGray;
  final Color silver;
  final Color primaryLigth;
  final Color ice;
  final Color greenishWhite;
  final Color blackSecondary;
  final Color darkBlack;
  final Color disabledButtonColor;
  final Color blueAccent;
  final Color lightGray;
  final Color quickSilver;
  final Color blackOlive;
  final Color japaneseIndigo;
  final Color sunsetOrange;
  final Color pearlAqua;
  final Color graniteGray;
  final Color blackOpaque;
  final Color lightSilver;
  final Color silverChalice;
  final Color charlestonGreen;
  final Color whiteGrey;
  final Color blackGrey;
  final Color aeroBlue;
  final Color cultured;
  final Color silverSand;
  final Color philippineGray;
  final Color richBlack;
  final Color mediumAquamarina;
  final Color deepSaffron;
  final Color darkCharcoal;
  final Color caribbeanGreen;
  final Color aliceBlue;
  final Color tintedIce;
  final Color raisinBlack;
  final Color antiFlashWhite;
  final Color chineseSilver;
  final Color philippineYellow;
  final Color mangoGreen;
  final Color vividMalachite;
  final Color candyPink;
  final Color mistyRose;
  final Color cosmicLatte;
  final Color mintCream;
  final Color myrtleGreen;
  final Color outerSpace;
  final Color sacramentoStateGreen;
  final Color salem;
  final Color mediumGrey;
  final Color lemon;
  final Color greenLight;
  final Color orange;
  final Color orangeLight;
  final Color checkedGreen;
  final Color oceanInABowl;
  final Color errorLight;
  final Color deepIndianRed;
  final Color bangladeshGreen;
  final Color gray;
  final Color davysGrey;
  final Color lightSlver;
  final Color paleAquamarine;
  final Color cadmiumOrange;
  final Color bronze;
  final Color lightGra;
  final Color mustard;
  final Color meatBrown;
  final Color sonicSilver;
  final Color eerieBlack;
  final Color celadonGreen;
  final Color warmBlack;
}
